[package]
name = "eos-rust"
version = "0.1.0"
authors = ["datudou <wangqianyi.cs@gmail.com>"]


[workspace]
members = [
    "eos-api",
    "eos-cli",
]

[dependencies]
bytes = "0.4.9"
eos-api = { path = "eos-api" }
clap = {version = "2.32", features = ["yaml"]}



