[package]
name = "eos-cli"
version = "0.1.0"
authors = ["datudou <wangqianyi.cs@gmail.com>"]

[dependencies]
serde_json = "1.0"
eos-api = { path = "../eos-api" }
clap = {version = "2.32", features = ["yaml"]}

